### PR TITLE
Make it testable with Travis

### PR DESCRIPTION
**Pull request by syphernl**

### CODE REVIEW

**Comment by syphernl** [comment]
Feel free to reassign to @eXistenZNL if you don't want it @rtuin  ;-)

**Comment by berry-langerak** [comment]
oh sorry :) Felt like I needed to :dancers:

**Comment by rtuin** [comment]
This looks OK @syphernl!

When I grep the build log for 'error' I get 119 hits. For example:

```
# Password input error
mariadb-server-10.1 mysql-server/password_mismatch  error   false
mysql-server-5.0    mysql-server/password_mismatch  error   false
```

I think these are harmless since the state runs well, do you agree?

**Comment by syphernl** [comment]
Odd, seems to be something out of our control trough since we didn't install mysql-server-5.0 either :)

**Comment by eXistenZNL** [comment]
Still a bit sad we need to use sudo and thus the legacy platform, but oh well :)

**Pull request merged**
